version: 0.0
os: linux
files:
  - source: app
    destination: /var/www
  - source: deploy-scripts/spotops.api.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy_scripts/stop_application.sh
      timeout: 300
      runas: root